"""Add album columns

Revision ID: b0fba867a9c2
Revises: 
Create Date: 2025-09-20 18:37:52.905508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fba867a9c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('album_artist', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('album_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('album_image')
        batch_op.drop_column('album_artist')
        batch_op.drop_column('album_name')

    # ### end Alembic commands ###
